[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "signal-processing-utils"
version = "0.1.0"
authors = [
  { name="Shiva Prasad", email="vangarashivaprasad.130773@marwadiuniversity.ac.in" },
]
description = "A Python package for generating and manipulating fundamental signals."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.22.0",
    "matplotlib>=3.5.0",
]

[project.urls]
Homepage = "https://github.com/Shivaprasad98v/python"
"Bug Tracker" = "https://github.com/Shivaprasad98v/python"

[tool.setuptools.packages.find]
where = ["src"]
